/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package talib

__64BIT__ :: 1

Int32  :: i32
UInt32 :: u32

/* See "Windows Data Types". Platform SDK. MSDN documentation. */
Int64  :: i64
UInt64 :: u64

/* min/max value for a TA_Integer */
TA_INTEGER_MIN :: ((-2147483647-1)+1)
TA_INTEGER_MAX :: (2147483647)

/* min/max value for a TA_Real
*
* Use fix value making sense in the
* context of TA-Lib (avoid to use DBL_MIN
* and DBL_MAX standard macro because they
* are troublesome with some compiler).
*/
TA_REAL_MIN :: (-3e+37)
TA_REAL_MAX :: (3e+37)

/* A value outside of the min/max range
* indicates an undefined or default value.
*/
TA_INTEGER_DEFAULT :: ((-2147483647-1))
TA_REAL_DEFAULT    :: (-4e+37)

/* Part of this file is generated by ta_codegen */
TA_RetCode :: enum u32 {
	SUCCESS                   = 0, /* No error */
	LIB_NOT_INITIALIZE        = 1, /* TA_Initialize was not successfully called */
	BAD_PARAM                 = 2, /* A parameter is out of range */
	ALLOC_ERR                 = 3, /* Possibly out-of-memory */
	GROUP_NOT_FOUND           = 4,
	FUNC_NOT_FOUND            = 5,
	INVALID_HANDLE            = 6,
	INVALID_PARAM_HOLDER      = 7,
	INVALID_PARAM_HOLDER_TYPE = 8,
	INVALID_PARAM_FUNCTION    = 9,
	INPUT_NOT_ALL_INITIALIZE  = 10,
	OUTPUT_NOT_ALL_INITIALIZE = 11,
	OUT_OF_RANGE_START_INDEX  = 12,
	OUT_OF_RANGE_END_INDEX    = 13,
	INVALID_LIST_TYPE         = 14,
	BAD_OBJECT                = 15,
	NOT_SUPPORTED             = 16,
	INTERNAL_ERROR            = 5000,
	UNKNOWN_ERR               = 65535,
}

/* 0xFFFF */
TA_Compatibility :: enum u32 {
	DEFAULT   = 0,
	METASTOCK = 1,
}

/* 0xFFFF */
TA_MAType :: enum u32 {
	SMA   = 0,
	EMA   = 1,
	WMA   = 2,
	DEMA  = 3,
	TEMA  = 4,
	TRIMA = 5,
	KAMA  = 6,
	MAMA  = 7,
	T3    = 8,
}

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* Generated */
/* Generated */
TA_FuncUnstId :: enum i32 {
	ADX          = 0,
	ADXR         = 1,
	ATR          = 2,
	CMO          = 3,
	DX           = 4,
	EMA          = 5,
	HT_DCPERIOD  = 6,
	HT_DCPHASE   = 7,
	HT_PHASOR    = 8,
	HT_SINE      = 9,
	HT_TRENDLINE = 10,
	HT_TRENDMODE = 11,
	IMI          = 12,
	KAMA         = 13,
	MAMA         = 14,
	MFI          = 15,
	MINUS_DI     = 16,
	MINUS_DM     = 17,
	NATR         = 18,
	PLUS_DI      = 19,
	PLUS_DM      = 20,
	RSI          = 21,
	STOCHRSI     = 22,
	T3           = 23,
	ALL          = 24,
	NONE         = -1,
}

/* The TA_RangeType enum specifies the types of range that can be considered
* when to compare a part of a candle to other candles
*/
TA_RangeType :: enum u32 {
	RealBody = 0,
	HighLow  = 1,
	Shadows  = 2,
}

/* The TA_CandleSettingType enum specifies which kind of setting to consider;
* the settings are based on the parts of the candle and the common words
* indicating the length (short, long, very long)
*/
TA_CandleSettingType :: enum u32 {
	BodyLong          = 0,
	BodyVeryLong      = 1,
	BodyShort         = 2,
	BodyDoji          = 3,
	ShadowLong        = 4,
	ShadowVeryLong    = 5,
	ShadowShort       = 6,
	ShadowVeryShort   = 7,
	Near              = 8,
	Far               = 9,
	Equal             = 10,
	AllCandleSettings = 11,
}

